name: tech_hub
description: "Tech Hub Aplicacion Tecnica"
publish_to: 'none'
version: 4.1.1

environment:
  sdk: ^3.7.0

dependencies:
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_svg: ^2.2.0
  geolocator: ^14.0.2
  http: ^1.5.0
  image_picker: ^1.2.0
  file_picker: ^8.0.0+1
  image: ^4.3.0
  latlong2: ^0.9.1
  lucide_icons: ^0.257.0
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/geojson/
    - lib/assets/mapIcons/
    - lib/assets/images/